version: "3.1"

services:
  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379
  gamemaster:
    image: l12u/gamemaster:0.3.1
    build: .
    environment:
      ENABLE_REDIS_STORAGE: "true"
      REDIS_ADDRESS: "redis:6379"
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./boards.json:/etc/gamemaster/boards.json